# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d877de2a239ec7cbaa4f8614486402524cb3a3e833646c6f94529756874327752314d55fedf49f821dd29de382dfd64cab8de5b1ae399a1a712b8aa3cc35dd0

test:
  secret_key_base: d8f271fce02307bb84e88a862defc035a00d91604a3aada0e50aa15da6900a81023b43e948cbe466bcc8482eb776cc8a108abcdadec4bab8e188f8fbf2c1e417

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
